DROP LOGIN WebLogin
CREATE LOGIN WebLogin WITH PASSWORD = 'SQLPass1234!'
GO

DROP USER IF EXISTS WebUser
CREATE USER WebUser FROM LOGIN WebLogin
GO

DROP ROLE IF EXISTS WebUserRole
CREATE ROLE WebUserRole
GO

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE TO WebUserRole
EXEC sp_addrolemember N'WebUserRole', N'WebUser' 
GO